"""Added Github fields

Revision ID: c938ce6fd2be
Revises: b0b969306e20
Create Date: 2025-06-20 20:43:28.833540

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c938ce6fd2be'
down_revision: Union[str, None] = 'b0b969306e20'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('github_id', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('github_login', sa.String(), nullable=True))
    op.add_column('users', sa.Column('is_github_connected', sa.Boolean(), server_default='false', nullable=True))
    op.alter_column('users', 'password',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'password',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('users', 'is_github_connected')
    op.drop_column('users', 'github_login')
    op.drop_column('users', 'github_id')
    # ### end Alembic commands ###
